name: ipe
version: 0.1.0.0
github: "henriquecbuss/ipe-compiler"
license: BSD3
author: "Henrique da Cunha Buss"
maintainer: "henriquebusss@gmail.com"
copyright: "2022 Henrique da Cunha Buss"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/henriquecbuss/ipe-compiler#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - megaparsec >= 9.3.0 && < 10
    - text >= 2.0.1 && < 3
    - containers >= 0.6.6 && < 1
    - parser-combinators >= 1.3.0 && < 2
    - transformers >= 0.6.1.0 && < 0.7
    - pretty >= 1.1.3.6 && < 1.2.0.0

executables:
  ipe-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ipe
      - iris >= 0.1.0.0 && < 0.2.0.0

tests:
  ipe-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - ipe
      - hspec
      - megaparsec >= 9.3.0 && < 10
      - hspec-megaparsec >= 2.2.0 && < 3
      - text >= 2.0.1 && < 3
      - containers >= 0.6.6 && < 1
